version: "3"
services:
  cryptodocker:
    container_name: cryptodocker
    hostname: cryptodocker
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    build: 
      context: ./
      dockerfile: Dockerfile
    image: cryptodocker
    ports: 
      - "8000:8000"
    networks:
      jimber:
        aliases:
          - jimber
networks:
  jimber:
    external:
      name: jimber
